# Neural Network approach to function 7

In [3]:
import numpy as np
import tensorflow as tf
import pickle
import os

### Data preparation

In [4]:
input = np.load('./initial_inputs.npy')
output = np.load('./initial_outputs.npy')
print(input)
print(output)
#print(input.shape)
#print(input.shape[1])
func_dimensions = input.shape[1]
print('this function has ', func_dimensions, ' dimensions')

[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

Additional data provided by weekly queries

In [5]:
additionalInputs = [[0.5, 0.5, 0.5, 0.5, 0.5, 0.5], [0.064108, 0.50467, 0.307547, 0.22933, 0.356495, 0.789273], [0.045203, 0.493887, 0.296157, 0.140072, 0.360602, 0.761422], [0.129753, 0.463468, 0.317766, 0.191937, 0.396281, 0.784369], [0.06782, 0.434119, 0.249574, 0.196558, 0.385974, 0.837422], [0.042636, 0.459636, 0.304379, 0.221496, 0.43641, 0.790166], [0.120728, 0.533888, 0.275139, 0.168882, 0.441824, 0.790651]]
additionalOutputs = [np.float64(0.5053149917022333), np.float64(1.5242238626243496), np.float64(1.348343558184188), np.float64(1.5755656391558395), np.float64(1.372546781524056), np.float64(1.3069906162600267), np.float64(1.0246878483199038)]

input = np.append(input, additionalInputs, axis=0)
output = np.append(output, additionalOutputs)

print(input)
print(output)

[[0.27262382 0.32449536 0.89710881 0.83295115 0.15406269 0.79586362]
 [0.54300258 0.9246939  0.34156746 0.64648585 0.71844033 0.34313266]
 [0.09083225 0.66152938 0.06593091 0.25857701 0.96345285 0.6402654 ]
 [0.11886697 0.61505494 0.90581639 0.8553003  0.41363143 0.58523563]
 [0.63021764 0.8380969  0.68001305 0.73189509 0.52673671 0.34842921]
 [0.76491917 0.25588292 0.60908422 0.21807904 0.32294277 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811844 0.42042833 0.73096984]
 [0.19525188 0.07922665 0.55458046 0.17056682 0.01494418 0.10703171]
 [0.64230298 0.83687455 0.02179269 0.10148801 0.68307083 0.6924164 ]
 [0.78994255 0.19554501 0.57562333 0.07365919 0.25904917 0.05109986]
 [0.52849733 0.45742436 0.36009569 0.36204551 0.81689098 0.63747637]
 [0.72261522 0.01181284 0.06364591 0.16517311 0.07924415 0.35995166]
 [0.07566492 0.33450212 0.13273274 0.60831236 0.91838592 0.82233079]
 [0.94245084 0.37743962 0.48612233 0.22879108 0.08263175 0.71195755]
 [0.14864702 0.03394336 0.72880565

# Neural network setup
Here we prepare a neural network to approach function 5

This requires 4 inputs and 1 output

We decide to apply 2 hidden layers of 8 nodes each

The activation function will be a tanh


In [6]:
# 1. Define the input data and target output for demonstration
x_train = np.array(input, dtype=np.float32)
y_train = np.array(output, dtype=np.float32).reshape(-1, 1)

# Normalize the output (CRITICAL for training)
y_mean = np.mean(y_train)
y_std = np.std(y_train)
y_train_normalized = (y_train - y_mean) / y_std

print(f"Output normalized: mean={y_mean:.2f}, std={y_std:.2f}")



Output normalized: mean=0.41, std=0.50


In [7]:
print(x_train)
print(y_train)
print(len(x_train))
print(len(y_train))

[[0.2726238  0.32449538 0.8971088  0.8329511  0.15406269 0.7958636 ]
 [0.5430026  0.9246939  0.34156746 0.64648587 0.71844035 0.34313267]
 [0.09083225 0.66152936 0.06593091 0.25857702 0.9634529  0.6402654 ]
 [0.11886697 0.61505497 0.9058164  0.8553003  0.41363144 0.58523566]
 [0.6302176  0.8380969  0.68001306 0.7318951  0.52673674 0.3484292 ]
 [0.76491916 0.25588292 0.60908425 0.21807905 0.32294276 0.09579366]
 [0.05789554 0.49167222 0.24742222 0.21811843 0.42042834 0.73096985]
 [0.19525188 0.07922665 0.55458045 0.17056683 0.01494418 0.10703171]
 [0.642303   0.83687454 0.02179269 0.10148801 0.68307084 0.6924164 ]
 [0.78994256 0.195545   0.57562333 0.07365919 0.25904918 0.05109986]
 [0.52849734 0.45742434 0.36009568 0.3620455  0.81689095 0.6374764 ]
 [0.72261524 0.01181284 0.06364591 0.16517311 0.07924414 0.35995165]
 [0.07566492 0.33450213 0.13273273 0.60831237 0.9183859  0.8223308 ]
 [0.9424508  0.37743962 0.48612234 0.22879109 0.08263174 0.7119576 ]
 [0.14864703 0.03394336 0.72880566

In [8]:
# Initialize weights with better initialization (Xavier/Glorot)
W1 = tf.Variable(tf.random.normal([7, 12], stddev=np.sqrt(2.0/5)), dtype=tf.float32)  # 6 inputs + 1 bias
W2 = tf.Variable(tf.random.normal([13, 12], stddev=np.sqrt(2.0/9)), dtype=tf.float32)  # 12 hidden + 1 bias
W3 = tf.Variable(tf.random.normal([12, 1], stddev=np.sqrt(2.0/8)), dtype=tf.float32)  # 12 hidden to 1 output
print(W1)
print(W2)
print(W3)


<tf.Variable 'Variable:0' shape=(7, 12) dtype=float32, numpy=
array([[ 0.19514214, -0.9158555 ,  0.3927028 ,  0.41211736,  0.09855016,
         0.75134   , -0.55006856, -0.87633777, -0.18932079, -0.47857335,
        -0.7826843 , -0.19426337],
       [-0.4364993 , -1.5604193 , -1.1358479 , -0.59828526, -0.6293758 ,
         1.8799788 ,  0.4182103 , -0.49697667, -0.38835078, -0.6818243 ,
        -0.3321777 , -0.1114894 ],
       [ 0.17550883, -0.5766975 , -0.92166865, -0.36053947,  0.13205132,
         0.30277997, -0.26559386, -0.635268  , -0.4853976 , -0.15724894,
        -0.29438087,  0.9574915 ],
       [-0.00875299,  0.0670704 , -0.10600499,  0.07368073,  0.7904248 ,
         0.52831453, -0.6488384 , -0.49395132, -0.4955501 ,  0.40539843,
        -0.4631759 ,  0.18747711],
       [-0.15793487, -0.56764394, -0.3622086 , -1.3706213 ,  0.04485205,
        -0.25432944,  0.770005  , -0.53627   , -0.5249241 , -0.36927125,
         0.7928613 ,  0.3746082 ],
       [ 0.20596011, -1.5952859 ,

In [9]:
@tf.function
def forward_pass(x_batch):
    # x_batch shape: (batch_size, 4)
    batch_size = tf.shape(x_batch)[0]
    bias = tf.ones((batch_size, 1), dtype=tf.float32)

    # First hidden layer
    x_with_bias = tf.concat([x_batch, bias], axis=1)  # (batch_size, 5)
    hidden1 = tf.nn.tanh(tf.matmul(x_with_bias, W1))  # (batch_size, 8)

    # Second hidden layer
    hidden1_with_bias = tf.concat([hidden1, bias], axis=1)  # (batch_size, 9)
    hidden2 = tf.nn.tanh(tf.matmul(hidden1_with_bias, W2))  # (batch_size, 8)

    # Output layer (LINEAR, no sigmoid!)
    output = tf.matmul(hidden2, W3)  # (batch_size, 1)

    return output


#print(forward_pass(x_train[0].reshape(4,-1)))

In [10]:
# Loss and optimizer
loss_fn = tf.keras.losses.MeanSquaredError()
optimizer = tf.optimizers.SGD(learning_rate=0.01)  # Lower learning rate
print(loss_fn)
print(optimizer)

<LossFunctionWrapper(<function mean_squared_error at 0x7a4ce0938f40>, kwargs={})>


In [11]:
@tf.function
def train_step(x, y):
    with tf.GradientTape() as tape:
        y_pred = forward_pass(x)
        loss = loss_fn(y, y_pred)
    gradients = tape.gradient(loss, [W1, W2, W3])
    optimizer.apply_gradients(zip(gradients, [W1, W2, W3]))
    return loss


###END SOLUTION
#for i, v in enumerate(x_train):
#  print(train_step(x_train[i].reshape(4,-1), y_train[i]))
#for epoch in range(10):
#  print(train_step(x_train[0].reshape(4,-1), y_train[0].reshape(1,1)))
# Training loop
print("\nTraining...")
epochs = 50000
for epoch in range(epochs):
    loss = train_step(x_train, y_train_normalized)

    if epoch % 500 == 0:
        print(f"Epoch {epoch}, Loss: {loss.numpy():.6f}")



Training...
Epoch 0, Loss: 2.892851
Epoch 500, Loss: 0.233991
Epoch 1000, Loss: 0.160952
Epoch 1500, Loss: 0.123211
Epoch 2000, Loss: 0.097827
Epoch 2500, Loss: 0.081768
Epoch 3000, Loss: 0.072243
Epoch 3500, Loss: 0.066095
Epoch 4000, Loss: 0.061777
Epoch 4500, Loss: 0.058589
Epoch 5000, Loss: 0.056155
Epoch 5500, Loss: 0.054239
Epoch 6000, Loss: 0.052681
Epoch 6500, Loss: 0.051368
Epoch 7000, Loss: 0.050224
Epoch 7500, Loss: 0.049201
Epoch 8000, Loss: 0.048265
Epoch 8500, Loss: 0.047399
Epoch 9000, Loss: 0.046589
Epoch 9500, Loss: 0.045827
Epoch 10000, Loss: 0.045105
Epoch 10500, Loss: 0.044419
Epoch 11000, Loss: 0.043764
Epoch 11500, Loss: 0.043138
Epoch 12000, Loss: 0.042536
Epoch 12500, Loss: 0.041955
Epoch 13000, Loss: 0.041393
Epoch 13500, Loss: 0.040847
Epoch 14000, Loss: 0.040314
Epoch 14500, Loss: 0.039792
Epoch 15000, Loss: 0.039277
Epoch 15500, Loss: 0.038767
Epoch 16000, Loss: 0.038260
Epoch 16500, Loss: 0.037753
Epoch 17000, Loss: 0.037246
Epoch 17500, Loss: 0.036737
Epo

In [12]:
# ============================================================================
# SAVE WEIGHTS FUNCTION
# ============================================================================
def save_weights(filepath='model_weights.pkl'):
    """
    Save the trained weights and normalization parameters to a file.

    Args:
        filepath: Path where to save the weights (default: 'model_weights.pkl')
    """
    weights_dict = {
        'W1': W1.numpy(),
        'W2': W2.numpy(),
        'W3': W3.numpy(),
        'y_mean': y_mean,
        'y_std': y_std
    }

    with open(filepath, 'wb') as f:
        pickle.dump(weights_dict, f)

    print(f"\n✓ Weights saved to '{filepath}'")


In [13]:
# ============================================================================
# LOAD WEIGHTS FUNCTION
# ============================================================================
def load_weights(filepath='model_weights.pkl'):
    """
    Load previously saved weights and normalization parameters.

    Args:
        filepath: Path to the saved weights file

    Returns:
        tuple: (y_mean, y_std) normalization parameters
    """
    global W1, W2, W3, y_mean, y_std

    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Weights file '{filepath}' not found!")

    with open(filepath, 'rb') as f:
        weights_dict = pickle.load(f)

    # Load weights into TensorFlow variables
    W1.assign(weights_dict['W1'])
    W2.assign(weights_dict['W2'])
    W3.assign(weights_dict['W3'])

    # Load normalization parameters
    y_mean = weights_dict['y_mean']
    y_std = weights_dict['y_std']

    print(f"\n✓ Weights loaded from '{filepath}'")
    return y_mean, y_std


In [14]:
# ============================================================================
# PREDICTION FUNCTION (for inference with loaded model)
# ============================================================================
def predict(x_input, y_mean, y_std):
    """
    Make predictions on new data using the loaded model.

    Args:
        x_input: Input data (numpy array of shape [n_samples, 4])
        y_mean: Mean used for normalization
        y_std: Standard deviation used for normalization

    Returns:
        Predictions in original scale
    """
    x_input = np.array(x_input, dtype=np.float32)
    if len(x_input.shape) == 1:
        x_input = x_input.reshape(1, -1)

    predictions_normalized = forward_pass(x_input).numpy()
    predictions = predictions_normalized * y_std + y_mean

    return predictions


In [15]:
# ============================================================================
# TRAINING MODE
# ============================================================================
TRAIN_MODE = True  # Set to False to skip training and only load weights

if TRAIN_MODE:
    print("\nTraining...")
    epochs = 500
    for epoch in range(epochs):
        loss = train_step(x_train, y_train_normalized)

        if epoch % 500 == 0:
            print(f"Epoch {epoch}, Loss: {loss.numpy():.6f}")

    # Make predictions
    print("\n" + "="*70)
    print("Training Results:")
    print("="*70)
    predictions_normalized = forward_pass(x_train).numpy()
    predictions = predictions_normalized * y_std + y_mean

    print(f"{'Actual':<15} {'Predicted':<15} {'Error':<15}")
    print("-"*70)
    for i in range(len(y_train)):
        actual = y_train[i, 0]
        predicted = predictions[i, 0]
        error = abs(actual - predicted)
        print(f"{actual:<15.2f} {predicted:<15.2f} {error:<15.2f}")

    mse = np.mean((predictions - y_train) ** 2)
    mae = np.mean(np.abs(predictions - y_train))
    print("="*70)
    print(f"Mean Squared Error: {mse:.2f}")
    print(f"Mean Absolute Error: {mae:.2f}")

    # Save the trained weights
    save_weights('model_weights.pkl')

# ============================================================================
# INFERENCE MODE (Load weights and make predictions)
# ============================================================================
else:
    print("\n" + "="*70)
    print("INFERENCE MODE - Loading saved weights")
    print("="*70)

    # Load previously saved weights
    y_mean, y_std = load_weights('model_weights.pkl')

    # Make predictions on the training data (or new data)
    print("\nMaking predictions with loaded model...")
    predictions = predict(x_train, y_mean, y_std)

    print(f"\n{'Actual':<15} {'Predicted':<15} {'Error':<15}")
    print("-"*70)
    for i in range(len(y_train)):
        actual = y_train[i, 0]
        predicted = predictions[i, 0]
        error = abs(actual - predicted)
        print(f"{actual:<15.2f} {predicted:<15.2f} {error:<15.2f}")

    # Example: Make a prediction on a new sample
    print("\n" + "="*70)
    print("Example prediction on new data:")
    print("="*70)
    new_sample = np.array([[0.5, 0.5, 0.5, 0.5]])
    new_prediction = predict(new_sample, y_mean, y_std)
    print(f"Input: {new_sample[0]}")
    print(f"Predicted output: {new_prediction[0, 0]:.2f}")


Training...
Epoch 0, Loss: 0.005412

Training Results:
Actual          Predicted       Error          
----------------------------------------------------------------------
0.60            0.60            0.00           
0.56            0.58            0.02           
0.01            -0.02           0.03           
0.06            0.07            0.01           
0.27            0.29            0.01           
0.08            0.08            0.01           
1.36            1.28            0.09           
0.09            0.09            0.00           
0.02            0.01            0.01           
0.03            0.04            0.00           
0.07            0.11            0.04           
0.21            0.21            0.00           
0.01            0.01            0.00           
0.27            0.27            0.00           
0.61            0.61            0.00           
0.01            0.02            0.00           
0.27            0.28            0.00           
0.07     

In [16]:
# ============================================================================
# GRID SEARCH FOR MAXIMUM OUTPUT
# ============================================================================
print("\n" + "="*70)
print("Searching for maximum output on grid...")
print("="*70)

# Initialize grid for plots
vector_values = np.linspace(0, 1, 22)  # 101 values from 0 to 1

# Generalized version for any number of dimensions
grids = np.meshgrid(*([vector_values] * func_dimensions), indexing='ij')
x_grid = np.column_stack([grid.ravel() for grid in grids])

print(f"Grid size: {x_grid.shape[0]:,} points ({len(vector_values)}^4)")
print("Evaluating model on entire grid...")


Searching for maximum output on grid...
Grid size: 113,379,904 points (22^4)
Evaluating model on entire grid...


In [17]:
print(x_grid.shape)

(113379904, 6)


In [18]:

# Make predictions on the entire grid (may take a moment for 101^4 = ~104M points)
# Process in batches to avoid memory issues
batch_size = 100000
n_batches = int(np.ceil(len(x_grid) / batch_size))
all_predictions = []

for i in range(n_batches):
    start_idx = i * batch_size
    end_idx = min((i + 1) * batch_size, len(x_grid))
    batch_predictions = predict(x_grid[start_idx:end_idx], y_mean, y_std)
    all_predictions.append(batch_predictions)

    if (i + 1) % 10 == 0 or (i + 1) == n_batches:
        print(f"  Progress: {i+1}/{n_batches} batches processed")


  Progress: 10/1134 batches processed
  Progress: 20/1134 batches processed
  Progress: 30/1134 batches processed
  Progress: 40/1134 batches processed
  Progress: 50/1134 batches processed
  Progress: 60/1134 batches processed
  Progress: 70/1134 batches processed
  Progress: 80/1134 batches processed
  Progress: 90/1134 batches processed
  Progress: 100/1134 batches processed
  Progress: 110/1134 batches processed
  Progress: 120/1134 batches processed
  Progress: 130/1134 batches processed
  Progress: 140/1134 batches processed
  Progress: 150/1134 batches processed
  Progress: 160/1134 batches processed
  Progress: 170/1134 batches processed
  Progress: 180/1134 batches processed
  Progress: 190/1134 batches processed
  Progress: 200/1134 batches processed
  Progress: 210/1134 batches processed
  Progress: 220/1134 batches processed
  Progress: 230/1134 batches processed
  Progress: 240/1134 batches processed
  Progress: 250/1134 batches processed
  Progress: 260/1134 batches proce

In [19]:

# Concatenate all predictions
grid_predictions = np.concatenate(all_predictions, axis=0)

# Find the maximum
max_idx = np.argmax(grid_predictions)
max_input = x_grid[max_idx]
max_output = grid_predictions[max_idx, 0]

print("\n" + "="*70)
print("MAXIMUM OUTPUT FOUND:")
print("="*70)
print(f"Input values:  [{max_input[0]:.6f}, {max_input[1]:.6f}, {max_input[2]:.6f}, {max_input[3]:.6f}, {max_input[4]:.6f}, {max_input[5]:.6f}]")
print(f"Predicted output: {max_output:.2f}")
print("="*70)



MAXIMUM OUTPUT FOUND:
Input values:  [0.047619, 0.619048, 1.000000, 0.142857, 0.000000, 0.761905]
Predicted output: 2.50


In [ ]:
# Also show top 5 candidates
print("\nTop 5 inputs with highest predicted outputs:")
print("-"*70)
top_5_indices = np.argsort(grid_predictions[:, 0])[-5:][::-1]
for rank, idx in enumerate(top_5_indices, 1):
    inp = x_grid[idx]
    out = grid_predictions[idx, 0]
    print(f"{rank}. Input: [{inp[0]:.4f}, {inp[1]:.4f}, {inp[2]:.4f}, {inp[3]:.4f}] → Output: {out:.2f}")